import { app, BrowserWindow, ipcMain, nativeImage } from 'electron';
import { autoUpdater } from 'electron-updater';
import * as path from 'path';
import * as fs from 'fs';

// Import electron-store dynamically to avoid potential ESM/CJS transpilation issues
let store: any;
const storeReady = (async () => {
  const Store = (await import('electron-store') as any).default;
  store = new Store();
})();

let mainWindow: BrowserWindow | null = null;

function createWindow() {
  mainWindow = new BrowserWindow({
    width: 1200,
    height: 800,
    minWidth: 950,
    minHeight: 650,
    frame: false, // frameless window
    backgroundColor: '#000000',
    // Note: macOS dock icon is set via electron-builder config (build/mac/icon)
    // BrowserWindow icon is only used for Windows/Linux
    icon: process.platform === 'darwin' ? undefined : path.join(__dirname, '../public/icon.png'),
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      nodeIntegration: false,
      contextIsolation: true,
      webSecurity: true,
    },
  });

  // Check if we are in development mode
  const isDev = process.env.NODE_ENV === 'development' || !app.isPackaged;

  if (isDev) {
    mainWindow.loadURL('http://localhost:5173').catch(() => {
      // If Vite server is not ready yet, retry after 1 second
      setTimeout(() => {
        if (mainWindow) mainWindow.loadURL('http://localhost:5173');
      }, 1500);
    });
    // Open devtools in dev mode if desired
    // mainWindow.webContents.openDevTools();
  } else {
    mainWindow.loadFile(path.join(__dirname, '../dist/index.html'));
  }

  mainWindow.on('closed', () => {
    mainWindow = null;
  });
}

app.whenReady().then(() => {
  // Set macOS dock icon in development mode
  // Use build/icons/icon.icns (generated by generate-icons.sh) — do NOT point to
  // public/icon.icns because that copy may be stale or missing.
  if (process.platform === 'darwin' && !app.isPackaged) {
    const iconPath = path.join(__dirname, '../build/icon-source.png');
    if (fs.existsSync(iconPath)) {
      try {
        const image = nativeImage.createFromPath(iconPath);
        if (!image.isEmpty()) {
          app.dock?.setIcon(image);
        } else {
          console.warn('[electron] Failed to load image for dock icon from:', iconPath);
        }
      } catch (err) {
        console.warn('[electron] Failed to set dock icon:', err);
      }
    } else {
      console.warn('[electron] Dock icon source not found at:', iconPath);
    }
  }

  createWindow();

  // Check for auto-updates when app is ready (only in packaged mode)
  if (app.isPackaged) {
    autoUpdater.checkForUpdatesAndNotify();
  }

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) {
      createWindow();
    }
  });
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

// IPC Window Controls
ipcMain.on('window-minimize', () => {
  if (mainWindow) mainWindow.minimize();
});

ipcMain.on('window-maximize', () => {
  if (mainWindow) {
    if (mainWindow.isMaximized()) {
      mainWindow.unmaximize();
    } else {
      mainWindow.maximize();
    }
  }
});

ipcMain.on('window-close', () => {
  if (mainWindow) mainWindow.close();
});

type SettingsKey =
  | 'theme'
  | 'pieceSet'
  | 'showLegalMoves'
  | 'showCoordinates'
  | 'soundVolume'
  | 'enableSound'
  | 'confirmMoves'
  | 'autoPromoteToQueen'
  | 'boardFlipped'
  | 'isVoiceEnabled'
  | 'voiceGender'
  | 'enableAmbientSound'
  | 'ambientVolume'
  | 'isLoggedIn'
  | 'isGuest'
  | 'playerName'
  | 'playerEmail'
  | 'playerAvatar';

const ALLOWED_KEYS: Set<string> = new Set([
  'theme',
  'pieceSet',
  'showLegalMoves',
  'showCoordinates',
  'soundVolume',
  'enableSound',
  'confirmMoves',
  'autoPromoteToQueen',
  'boardFlipped',
  'isVoiceEnabled',
  'voiceGender',
  'enableAmbientSound',
  'ambientVolume',
  'isLoggedIn',
  'isGuest',
  'playerName',
  'playerEmail',
  'playerAvatar'
]);

function validateKey(key: any): key is SettingsKey {
  return typeof key === 'string' && ALLOWED_KEYS.has(key);
}

function validateValueForKey(key: SettingsKey, value: any): { ok: true } | { ok: false; reason: string } {
  const t = typeof value;

  switch (key) {
    case 'theme':
      if (value === 'mono' || value === 'forest' || value === 'ocean' || value === 'crimson' || value === 'aurora' || value === 'wooden' || value === 'walnut') return { ok: true };
      return { ok: false, reason: 'Invalid theme' };

    case 'pieceSet':
      if (value === 'classic' || value === 'neo' || value === 'alpha' || value === 'maya' || value === 'bases' || value === 'wooden-pieces') return { ok: true };
      return { ok: false, reason: 'Invalid pieceSet' };

    case 'voiceGender':
      if (value === 'male' || value === 'female') return { ok: true };
      return { ok: false, reason: 'Invalid voiceGender' };

    case 'soundVolume':
    case 'ambientVolume':
      if (t === 'number' && Number.isFinite(value)) return { ok: true };
      return { ok: false, reason: 'Invalid volume' };

    case 'showLegalMoves':
    case 'showCoordinates':
    case 'enableSound':
    case 'confirmMoves':
    case 'autoPromoteToQueen':
    case 'boardFlipped':
    case 'isVoiceEnabled':
    case 'enableAmbientSound':
    case 'isLoggedIn':
    case 'isGuest':
      if (t === 'boolean') return { ok: true };
      return { ok: false, reason: 'Invalid boolean' };

    case 'playerName':
    case 'playerEmail':
    case 'playerAvatar':
      if (t === 'string') return { ok: true };
      return { ok: false, reason: 'Invalid string' };

    default:
      return { ok: false, reason: 'Unknown key' };
  }
}

ipcMain.handle('settings-get', async (_event, key: any) => {
  await storeReady;
  if (!validateKey(key)) return null;
  return store ? store.get(key) : null;
});

ipcMain.handle('settings-set', async (_event, key: any, value: any) => {
  await storeReady;
  if (!store) return false;
  if (!validateKey(key)) return false;

  const validation = validateValueForKey(key, value);
  if (!validation.ok) return false;

  store.set(key, value);
  return true;
});

ipcMain.handle('settings-delete', async (_event, key: any) => {
  await storeReady;
  if (!store) return false;
  if (!validateKey(key)) return false;
  store.delete(key);
  return true;
});

